function [] = plot_metrics(fg,sp,rel_err,m_dist,tv)
    metrics = {'Metrics','', ...
               ['RE:{} ',num2str(rel_err,'%.2e')], ...
               ['MD: {} ',num2str(m_dist,  '%.2e')], ...
               ['TV: {} ',num2str(tv, '%.2e')]};
%     metrics{1} = ['\underline{\bf ', metrics{1}, ' \rm}'];
    metrics{1} = ['\bf ', metrics{1}, ' \rm'];
    figure(fg)
    if sp, subplot(sp(1),sp(2),sp(3:end)), end
    text(.5,.5,metrics, ...
        'fontsize',16, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle')
    set(gca,'visible','off')
    drawnow
end